# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pgmanager
                                 A QGIS plugin
 PostgreSQL User Manager
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-11
        copyright            : (C) 2019 by GIS Support sp. z.o.o
        email                : info@gis-support.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load pgmanager class from file pgmanager.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pg_manager import pgmanager
    return pgmanager(iface)
